apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: <base64-encoded-docker-config-json>
# The value of config.json is the base64-encoded ~/.docker/config.json file. You can get this data with the following command:
# cat ~/.docker/config.json | base64 -w0