apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: open-flights-pipeline
spec:
  workspaces:
    - name: shared-workspace
      description: The workspace containing the source code
    - name: docker-credentials
      description: Docker credentials
  params:
    - name: git-url
      type: string
      description: URL of the git repo to clone
      default: "https://github.com/Nitesh-NEU/open-flights.git"
    - name: image-name
      type: string
      description: Name of the image to build
      default: "niteshmore22/rails-app:latest"
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
    
    - name: build-push-image
      taskRef:
        name: build-and-push
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: DOCKERFILE
          value: "./Dockerfile"
        - name: CONTEXT
          value: "."