apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Nitesh-NEU/RubyApp-ArgoCD.git'
    targetRevision: main
    path: K8s/manifests/ruby-app
    directory:
      include: "output.yaml"
    # helm:
    #   valueFiles:
    #     - K8s/manifests/ruby-app/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
