apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Nitesh-NEU/makerble.git
  username: Nitesh-NEU
  password: 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
